<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="MSI" failures="1" tests="6" name="Personal Loan" time="0.044" errors="0" timestamp="2024-08-31T12:34:39 IST">
  <testcase classname="test.Intro_TestNG" name="Meth1" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Intro_TestNG.Meth1(Intro_TestNG.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Meth1 -->
  <testcase classname="test.demo" name="Meth2" time="0.001"/>
  <testcase classname="test.demo" name="PersonalPara" time="0.001"/>
  <testcase classname="test.Day4" name="APILogin_HomeLoan" time="0.001"/>
  <testcase classname="test.Day4" name="MobileLogin_HomeLoan" time="0.004"/>
  <testcase classname="test.Day4" name="WebLogin_HomeLoan" time="0.001"/>
  <testcase classname="test.Intro_TestNG" name="Name" time="0.0">
    <ignored/>
  </testcase> <!-- Name -->
</testsuite> <!-- Personal Loan -->
